type Emojis = {
  [key: string]: string;
};

const emojis: Emojis = {
  "artist palette": "🎨",
  "thumbs up": "👍",
  "heart": "❤️",
  "laughing face": "😂",
  "fire": "🔥",
  "rocket": "🚀",
  "clapping hands": "👏",
  "smiling face with sunglasses": "😎",
  "raised hands": "🙌",
  "party popper": "🎉",
  "thumbs down": "👎",
  "broken heart": "💔",
  "crying face": "😢",
  "angry face": "😠",
  "bomb": "💣",
  "star": "⭐️",
  "rainbow": "🌈",
  "praying hands": "🙏",
  "sparkles": "✨",
  "ghost": "👻",
  "100": "💯",
  "poop": "💩",
  "pizza": "🍕",
  "unicorn": "🦄",
  "sunflower": "🌻",
  "monkey face": "🐵",
  "small blue diamond": "🔹",
  "chart increasing": "📈",
  "chart decreasing": "📉",
  "see-no-evil monkey": "🙈",
  "framed picture": "🖼",
  "left-right arrow": "↔️",
  "up-down arrow": "↕️",
  "up arrow": "⬆️",
  "down arrow": "⬇️",
  "left arrow": "⬅️",
  "right arrow": "➡️",
  "up-left arrow": "↖️",
  "up-right arrow": "↗️",
  "down-right arrow": "↘️",
  "down-left arrow": "↙️",
  "left-right arrow with hook": "↪️",
  "right-arrow curving left": "↩️",
  "left arrow curving right": "↪️",
  "right arrow curving up": "⤴️",
  "right arrow curving down": "⤵️",
  "clockwise vertical arrows": "🔃",
  "counterclockwise arrows button": "🔄",
  "back arrow": "🔙",
  "end arrow": "🔚",
  "on! arrow": "🔛",
  "soon arrow": "🔜",
  "top arrow": "🔝",
  "dollar banknote": "💵",
  "point_up_2": "👆",
  "speaker high volume": "🔊",
  "speaker medium volume": "🔉",
  "speaker low volume": "🔈",
  "speaker": "🔈",
  "speaker mute": "🔇",
  "speaker loud": "📢",
  "speaker loudness": "🔊",
  "speaker one sound wave": "🔉",
  "speaker three sound waves": "🔊",
  "speaker cancellation": "🔇",
  "bell": "🔔",
  "bell ringing": "🔔",
  "bell with slash": "🔕",
  "musical note": "🎵",
  "musical notes": "🎶",
  "studio microphone": "🎙",
  "level slider": "🎚",
  "control knobs": "🎛",
  "microphone": "🎤",
  "headphone": "🎧",
  "radio": "📻",
  "saxophone": "🎷",
  "guitar": "🎸",
  "musical keyboard": "🎹",
  "trumpet": "🎺",
  "violin": "🎻",
  "drum": "🥁",
  "mobile phone": "📱",
  "mobile phone with arrow": "📲",
  "telephone": "☎️",
  "telephone receiver": "📞",
  "pager": "📟",
  "fax machine": "📠",
  "battery": "🔋",
  "electric plug": "🔌",
  "laptop": "💻",
  "desktop computer": "🖥",
  "printer": "🖨",
  "keyboard": "⌨️",
  "computer mouse": "🖱",
  "trackball": "🖲",
  "computer disk": "💽",
  "floppy disk": "💾",
  "optical disk": "💿",
  "dvd": "📀",
  "movie camera": "🎥",
  "film frames": "🎞",
  "film projector": "📽",
  "clapper board": "🎬",
  "television": "📺",
  "camera": "📷",
  "camera with flash": "📸",
  "video camera": "📹",
  "videocassette": "📼",
  "magnifying glass tilted left": "🔍",
  "magnifying glass tilted right": "🔎",
  "candle": "🕯",
  "light bulb": "💡",
  "flashlight": "🔦",
  "red paper lantern": "🏮",
  "diya lamp": "🪔",
  "notebook with decorative cover": "📔",
  "closed book": "📕",
  "open book": "📖",
  "green book": "📗",
  "blue book": "📘",
  "orange book": "📙",
  "books": "📚",
  "notebook": "📓",
  "ledger": "📒",
  "page with curl": "📃",
  "scroll": "📜",
  "page facing up": "📄",
  "newspaper": "📰",
  "rolled-up newspaper": "🗞",
  "bookmark tabs": "📑",
  "bookmark": "🔖",
  "label": "🏷",
  "money bag": "💰",
  "coin": "🪙",
  "yen banknote": "💴",
  "euro banknote": "💶",
  "pound banknote": "💷",
  "money with wings": "💸",
  "credit card": "💳",
  "receipt": "🧾",
  "envelope": "✉️",
  "e-mail": "📧",
  "incoming envelope": "📨",
  "envelope with arrow": "📩",
  "outbox tray": "📤",
  "inbox tray": "📥",
  "package": "📦",
  "video game": "🎮",
  "woman health worker": "👩‍⚕️",
  "snowflake": "❄️",
};

export default function createEmojisFromString(string: string): string {
  if (typeof string !== "string" || string?.replace === undefined) return string;
  const regex = /:([^:\s]+(\s+[^:\s]+)*):/g;
  return string.replace(regex, (match, emojiName) => {
    const emoji = emojis[emojiName];
    return emoji ? emoji : match;
  });
}
